### ISSUE TITLE
Error when re-opening project

### ISSUE THREAD

**Issue by pplam** [devchat-ai/devchat-intellij#53]
~~~
java.lang.Throwable: [DevChat] Failed to install DevChat CLI: null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at ai.devchat.common.Log.error(Log.kt:29)
	at ai.devchat.idea.DevChatSetupThread.run(DevChatSetupThread.kt:32)
~~~

<img width="998" alt="Screenshot 2024-01-08 at 11 48 06" src="https://github.com/devchat-ai/devchat-intellij/assets/12783579/581947b5-706e-4df8-a7cf-116a140d49e9">

**Comment by pplam** [comment]
Closed by PR#52
